apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-stolon-0
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-stolon-local
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: db-node
          operator: In
          values:
          - stolon

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-stolon-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-stolon-local
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: db-node
          operator: In
          values:
          - stolon
