kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-for-rooktest
  labels:
    app: postgres
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

