apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch-full-sample
  namespace: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  serviceName: elasticsearch-discovery
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
        - image: launcher.gcr.io/google/nginx1
          name: nginx
          volumeMounts:
            - name: site-conf
              mountPath: /etc/nginx/conf.d
            - name: site-top-html
              mountPath: /usr/share/nginx/html
            - name: htpasswd
              mountPath: /etc/nginx/htpasswd
        - image: elasticsearch:5.6
          name: elasticsearch-full
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: "NUMBER_OF_MASTERS"
            value: "1"
          - name: NODE_MASTER
            value: "true"
          - name: NODE_DATA
            value: "true"
          - name: "ES_JAVA_OPTS"
            value: "-Xms1024m -Xmx1024m"
          ports:
          - containerPort: 9200
            name: http
            protocol: TCP
          - containerPort: 9300
            name: transport
            protocol: TCP
          volumeMounts:
          - name: storage
            mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: site-conf
          configMap:
            name: site-conf
        - name: site-top-html
          configMap:
            name: site-top-html
        - name: htpasswd
          secret:
            secretName: htpasswd
        - name: storage
          persistentVolumeClaim:
            claimName: pvc-elastic-hostpath
      nodeSelector:
          type: node.mon.bench
