kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: hostpath
  namespace: elasticsearch
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/host-path
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-elastic-hostpath
  labels:
    app: 
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

