kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-elastic-hostpath
  namespace: elasticsearch
  labels:
    type: local
    app: pv-elastic
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/elasticsearch"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-elastic-hostpath
  namespace: elasticsearch
  labels:
    app: pv-elastic
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

