kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-pg-rook-sf
  labels:
    app: pg-rook-sf
spec:
  storageClassName: csi-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-pg-rook-sf-xlog
  labels:
    app: pg-rook-sf
spec:
  storageClassName: csi-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

