apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  flexVolume:
    driver: "nri.com/drbd"
    fsType: "xfs"
    options:
      volumeID: "drbd1000"
      size: "1000m"
      volumegroup: "drbdpool"
