apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-rook-ds
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: pg-rook-ds
  template:
    metadata:
      labels:
        app: pg-rook-ds
    spec:
      containers:
        - name: pg-rook-ds
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: TZ
              value: Asia/Tokyo
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-rook-vol
          livenessProbe:
              tcpSocket:
                 port: 5432
              initialDelaySeconds: 10
              periodSeconds: 3
              timeoutSeconds: 3
              failureThreshold: 2
          readinessProbe:
              tcpSocket:
                 port: 5432
              initialDelaySeconds: 5
              periodSeconds: 3
              timeoutSeconds: 1
              successThreshold: 1
      volumes:
        - name: pg-rook-vol
          persistentVolumeClaim:
            claimName: pvc-pg-rook-ds
      nodeSelector:
        type: node.db.postgres
