kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-pg-rook-ds
  labels:
    app: pg-rook-ds
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

