apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: "prome-port"
    protocol: "TCP"
    port: 9090
    targetPort: 9090
  selector:
    app: prometheus
