apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: "prome-port"
    protocol: "TCP"
    port: 3000
    targetPort: 3000
  selector:
    app: pg-grafana
